/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajout (void);
GtkWidget* create_Rech (void);
GtkWidget* create_fenetre_modifier (void);
GtkWidget* create_fenetre_afficher (void);
GtkWidget* create_gestion (void);
